test optimize
target x86_64

function %brz_fold() -> i32 {
ebb0:
    v0 = bconst.b1 false
    brz v0, ebb2
    jump ebb1
ebb1:
    v1 = iconst.i32 42
    return v1
ebb2:
    v2 = iconst.i32 24
    return v2
}
; sameln: function %brz_fold
; nextln: ebb0:
; nextln:     v0 = bconst.b1 false
; nextln:     jump ebb2
; nextln: 
; nextln: ebb1:
; nextln:     v1 = iconst.i32 42
; nextln:     return v1
; nextln: 
; nextln: ebb2:
; nextln:     v2 = iconst.i32 24
; nextln:     return v2
; nextln: }

function %brnz_fold() -> i32 {
ebb0:
    v0 = bconst.b1 true
    brnz v0, ebb2
    jump ebb1
ebb1:
    v1 = iconst.i32 42
    return v1
ebb2:
    v2 = iconst.i32 24
    return v2
}
; sameln: function %brnz_fold
; nextln: ebb0:
; nextln:     v0 = bconst.b1 true
; nextln:     jump ebb2
; nextln: 
; nextln: ebb1:
; nextln:     v1 = iconst.i32 42
; nextln:     return v1
; nextln: 
; nextln: ebb2:
; nextln:     v2 = iconst.i32 24
; nextln:     return v2
; nextln: }
