test compile
target x86_64

; regex: V=v\d+

function u0:0(i8) -> i8, i8 fast {
ebb0(v0: i8):
    v1 = clz v0
    ; check: v3 = uextend.i32 v0
    ; nextln: v4 = ishl_imm v3, 24
    ; nextln: v6 = iconst.i32 -1
    ; nextln: v7 = iconst.i32 31
    ; nextln: v8, v9 = x86_bsr v4
    ; nextln: v10 = selectif.i32 eq v9, v6, v8
    ; nextln: v5 = isub v7, v10
    ; nextln: v1 = ireduce.i8 v5
    v2 = ctz v0
    ; nextln: v11 = uextend.i32 v0
    ; nextln: v13 = iconst.i32 32
    ; nextln: v14, v15 = x86_bsf v11
    ; nextln: v12 = selectif.i32 eq v15, v13, v14
    ; nextln: v2 = ireduce.i8 v12
    return v1, v2
}
